### ISSUE TITLE
Failed to install requirements

### ISSUE THREAD

**Issue by stevage** [ThreeSixtyGiving/grantnav#396]
Installing in a clean Ubuntu Precise64 using Vagrant/Virtualbox. After doing the initial steps, including installing Python3, VirtualEnv and activating the VirtualEnv:

```
(.ve)vagrant@precise64:/vagrant_data/grantnav$ pip install -r requirements_dev.txt
...
Downloading/unpacking mccabe==0.5.0 (from -r requirements_dev.txt (line 38))
  Running setup.py egg_info for package mccabe

    Installed /tmp/easy_install-au9p81/pytest-runner-2.11.1/setuptools_scm-0.0.0-py3.2.egg
    /usr/lib/python3.2/distutils/dist.py:257: UserWarning: Unknown distribution option: 'use_scm_version'
      warnings.warn(msg)
...
pkg_resources.DistributionNotFound: setuptools-scm>=1.15.0
```

Installing just `requirements.txt` gave this error, which looks like it tried to build a Python2 package using Python3:

```
Downloading/unpacking urllib3==1.16 (from -r requirements.txt (line 26))
  Downloading urllib3-1.16.tar.gz (179Kb): 179Kb downloaded
  Running setup.py egg_info for package urllib3
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/vagrant_data/grantnav/.ve/build/urllib3/setup.py", line 24
        long_description=u'\n\n'.join([readme, changes]),
                               ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/vagrant_data/grantnav/.ve/build/urllib3/setup.py", line 24

    long_description=u'\n\n'.join([readme, changes]),

                           ^

SyntaxError: invalid syntax
```

Trying to install the requirements with a Python 2 virtual env failed this way:
```
...
running build_ext
building '_sass' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/libsass
creating build/temp.linux-x86_64-2.7/libsass/src
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I./libsass/include -I/usr/include/python2.7 -c pysass.cpp -o build/temp.linux-x86_64-2.7/pysass.o -c -O3 -fPIC -std=c++0x -Wall -Wno-parentheses -Werror=switch -DLIBSASS_VERSION="3.3.5"
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
error: command 'gcc' failed with exit status 1
```

I'm not really sure what to try next.

**Comment by Bjwebb** [comment]
Looks like precise comes with Python 3.2, I think this might be the problem. Can you try with a later version of Python 3? We deploy on Ubuntu Trusty (14.04) which comes with Python 3.4

**Comment by stevage** [comment]
Thanks. Ok, on a new Trusty VM, I'm now running into issues with the Pillow dependency. It keeps complaining that it's missing a certain dependency so I've had to do do:

```
sudo apt-get install zlib1g-dev
sudo apt-get install libjpeg-dev
```

Something seems wrong here.

With those dependencies, it gets stuck here:

```
...
running build_ext

building 'PIL._imaging' extension

creating build/temp.linux-x86_64-3.4/libImaging

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DHAVE_LIBJPEG -DHAVE_LIBZ -I/vagrant/grantnav/.ve/build/Pillow/libImaging -I/vagrant/grantnav/.ve/include -I/usr/local/include -I/usr/include -I/vagrant/grantnav/.ve/include -I/usr/include/python3.4m -c _imaging.c -o build/temp.linux-x86_64-3.4/_imaging.o

_imaging.c:76:20: fatal error: Python.h: No such file or directory

 #include "Python.h"

                    ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

Python version 3.4.3.

Any ideas?

**Comment by stevage** [comment]
I just discovered the full list of dependencies for Pillow:

`sudo apt-get install libtiff5-dev libjpeg8-dev zlib1g-dev \
    libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk`

Unfortunately it didn't help - same error.

**Comment by Bjwebb** [comment]
Try installing `python3-dev`

**Comment by stevage** [comment]
Oh, that did it, thanks!

**Comment by stevage** [comment]
Another step to document is `python manage.py migrate`.

The server now runs, but connecting gives:

```
Request Method: | GET
1.8.18
NotFoundError
TransportError(404, 'index_not_found_exception', 'no such index')
/vagrant/grantnav/.ve/lib/python3.4/site-packages/elasticsearch/connection/base.py in _raise_error, line 108

```

I guess I need to import some kind of data in order to generate an index.

**Comment by stevage** [comment]
Ok, that didn't work either:

```
$ python dataload/import_to_elasticsearch.py --clean ../data/grantnav-20171005235701.json
Killed
```

This is a tiny file with just two grants in it.

After increasing memory with a swap file, things go a bit better:

```
python dataload/import_to_elasticsearch.py ../data/grantnav-20171005235701.json
{'acknowledged': True}
'../data/grantnav-20171005235701.json'
(2, [])
```

At that point, it sat for maybe 3-4 minutes, before finally terminating. I'm really confused what it could be doing for so long?

**Comment by stevage** [comment]
Ok, hooray, it's finally up and running :)
