### ISSUE TITLE
elasticsearch Load limit reached

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantnav#746]
We appear to have reached the limit for loading data in the http request...

Trace from last daily GN load.
```
Traceback (most recent call last):
  File "/home/grantnav/grantnav//dataload/import_to_elasticsearch.py", line 420, in <module>
    import_to_elasticsearch(args.files, args.clean)
  File "/home/grantnav/grantnav//dataload/import_to_elasticsearch.py", line 335, in import_to_elasticsearch
    result = elasticsearch.helpers.bulk(es, grant_generator(), raise_on_error=False)
  File "/home/grantnav/grantnav/.ve/lib/python3.6/site-packages/elasticsearch/helpers/actions.py", line 300, in bulk
    for ok, item in streaming_bulk(client, actions, *args, **kwargs):
  File "/home/grantnav/grantnav/.ve/lib/python3.6/site-packages/elasticsearch/helpers/actions.py", line 230, in streaming_bulk
    **kwargs
  File "/home/grantnav/grantnav/.ve/lib/python3.6/site-packages/elasticsearch/helpers/actions.py", line 116, in _process_bulk_chunk
    raise e
  File "/home/grantnav/grantnav/.ve/lib/python3.6/site-packages/elasticsearch/helpers/actions.py", line 112, in _process_bulk_chunk
    resp = client.bulk("\n".join(bulk_actions) + "\n", *args, **kwargs)
  File "/home/grantnav/grantnav/.ve/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/grantnav/grantnav/.ve/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 1483, in bulk
    headers={"content-type": "application/x-ndjson"},
  File "/home/grantnav/grantnav/.ve/lib/python3.6/site-packages/elasticsearch/transport.py", line 350, in perform_request
    timeout=timeout,
  File "/home/grantnav/grantnav/.ve/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 257, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/grantnav/grantnav/.ve/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.TransportError: TransportError(429, 'circuit_breaking_exception', '[parent] Data too large, data for [<http_request>] would be [4011397984/3.7gb], which is larger than the limit of [3972635033/3.6gb], real usage: [4007063360/3.7gb], new bytes reserved: [4334624/4.1mb], usages [request=0/0b, fielddata=1206097/1.1mb, in_flight_requests=4334624/4.1mb, model_inference=0/0b, accounting=906512/885.2kb]')
```

**Comment by michaelwood** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix GN load breaking issue](https://trello.com/c/MorSJ3we/170-fix-gn-load-breaking-issue)

**Comment by michaelwood** [comment]
Notes
https://discuss.elastic.co/t/circuitbreakingexception-parent-data-too-large-in-es-7-x/192801/15

or looks like there are options to increase the memory size in jvm

via SO
```
ES_JAVA_OPTS="-Xmx2g -Xms2g".
```

**Comment by michaelwood** [comment]
We are currently testing settings the max_retries and initial_backoff on https://elasticsearch-py.readthedocs.io/en/master/helpers.html?highlight=max_retries#elasticsearch.helpers.streaming_bulk

This we hope will give the jvm garbage collector some breathing space to free up some memory.

**Comment by michaelwood** [comment]
related: https://github.com/ThreeSixtyGiving/grantnav/pull/755

**Comment by robredpath** [comment]
@michaelwood is this resolved?
